# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c679500bc7ddbfb2b8a09da2f05cb938953a75fc7183ae6b35614da90c029535d606cdf99ab7720f63797cad8b36007d8aab54d5725a21d2027a426dc2b04340

test:
  secret_key_base: b3a1a04e67b917606ef3349518330338176c51842fc9985227daf77d65f37955324e5af8738a72e1d671a4015f248355692e47ee9fba1575cc231f9d8b34faa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
